/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package McGill.ECSE428.Winter2020.Project.McFantasy;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
